### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Erikmitk** [slub/liszt_web#19]
Can you add a license to the repo? GPL-3.0 like the rest of the liszt-projects. :)

**Comment by dikastes** [comment]
Turns out. License has been there. In an old branch from a time long ago ;). Has been digged up now..

**Comment by Erikmitk** [comment]
[I fixed the links in the README](https://github.com/slub/liszt_web/commit/a6ab7f8b28f86d8365cebbeebac08c500eff6307) because I noticed that the badge for the license wasn't right. :)
